// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idmkiqcvfifohecxqihj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkbWtpcWN2Zmlmb2hlY3hxaWhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMzEzNTQsImV4cCI6MjA1NzgwNzM1NH0.KGyqMTXgYUvS93d_a6DY5tYYiAcHry_-z3isJkuaTOI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);